# Generated by Django 6.0.1 on 2026-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(choices=[('caloocan', 'Caloocan'), ('taguig', 'Taguig')], default='caloocan', max_length=10),
        ),
    ]
