# Generated by Django 6.0.1 on 2026-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10, null=True),
        ),
    ]
