# Generated by Django 6.0.1 on 2026-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_page', '0002_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstorage',
            name='date_stored',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_per_pallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
